/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ImageId = IDL.Nat;
export const ImageEntry = IDL.Record({
  'id' : ImageId,
  'data' : IDL.Vec(IDL.Nat8),
});

export const idlService = IDL.Service({
  '__images' : IDL.Func(
      [IDL.Opt(ImageId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(ImageId, ImageEntry))],
      ['query'],
    ),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  'listImages' : IDL.Func([], [IDL.Vec(ImageEntry)], ['query']),
  'uploadImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [ImageId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ImageId = IDL.Nat;
  const ImageEntry = IDL.Record({ 'id' : ImageId, 'data' : IDL.Vec(IDL.Nat8) });
  
  return IDL.Service({
    '__images' : IDL.Func(
        [IDL.Opt(ImageId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(ImageId, ImageEntry))],
        ['query'],
      ),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    'listImages' : IDL.Func([], [IDL.Vec(ImageEntry)], ['query']),
    'uploadImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [ImageId], []),
  });
};

export const init = ({ IDL }) => { return []; };